### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by kaanaksit** [ahmedadamji/Optical-Aberrations-Modeling#1]
Thank you, @ahmedadamji, for making it available to the public. You may consider having a `requirements.txt` in your repository and append these lines to it:

```
odak
torch
```

**Comment by ahmedadamji** [comment]
Thanks, @kaanaksit! I really appreciate your suggestion. I'll add the requirements.txt with the necessary dependencies like odak and torch. Also, thank you for making tools like odak available, which played a significant role in enabling me to complete tasks like this one.
